#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Estimador_de_Pensiones.Resource", IsApplication=true)]

namespace Estimador_de_Pensiones
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_material_light_noactionbar_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int LogoGrande = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070008
			public const int RadSex = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int button1 = 2131165188;
			
			// aapt resource value: 0x7f07000b
			public const int button2 = 2131165195;
			
			// aapt resource value: 0x7f070011
			public const int button3 = 2131165201;
			
			// aapt resource value: 0x7f07001b
			public const int button4 = 2131165211;
			
			// aapt resource value: 0x7f070023
			public const int buttonFin = 2131165219;
			
			// aapt resource value: 0x7f070007
			public const int editFechaNac = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int editIngresoBruto = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int imageView1 = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070012
			public const int radio60 = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int radio60F0 = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int radio60F1 = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int radio60F2 = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int radio60F3 = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int radio65 = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int radio65F0 = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int radio65F1 = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int radio65F2 = 2131165210;
			
			// aapt resource value: 0x7f07000c
			public const int radioAFP = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int radioButtonFem = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int radioButtonMas = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int radioHAB = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int radioINT = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int radioPRIMA = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int radioPRO = 2131165200;
			
			// aapt resource value: 0x7f070003
			public const int space1 = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int space2 = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int textView1 = 2131165189;
			
			// aapt resource value: 0x7f07001c
			public const int textView2 = 2131165212;
			
			// aapt resource value: 0x7f07001e
			public const int viewAFP = 2131165214;
			
			// aapt resource value: 0x7f070020
			public const int viewFondo = 2131165216;
			
			// aapt resource value: 0x7f07001d
			public const int viewIngreso = 2131165213;
			
			// aapt resource value: 0x7f07001f
			public const int viewPension = 2131165215;
			
			// aapt resource value: 0x7f070022
			public const int viewTREA = 2131165218;
			
			// aapt resource value: 0x7f070021
			public const int viewVAN = 2131165217;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Page2 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Page3 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Page4 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Page5 = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Theme_Custom1 = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
